apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rentalapp
  name: app-deployment
  labels:
    app: rentalapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
        app: rentalapp
    spec:
      containers:
      - name: myweb
        image: techproawsdevopsteam/rentalapp:v1
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: appconfig
          - secretRef:
              name: appsecret
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          tcpSocket:
            port: 8000
          failureThreshold: 5
          periodSeconds: 12
          initialDelaySeconds: 10
        resources:
          limits:
            memory: 500Mi
            cpu: 100m
          requests:
            memory: 250Mi
            cpu: 80m	
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z db-service 3306; do echo "Waiting for DB"; sleep 2; done;']
