apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rentalapp
  name: database-persistent-volume-claim
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual